### ISSUE TITLE
Could not invoke dnf

### ISSUE THREAD

**Issue by MadhanmohanGollamudi** [rdanter/wrl-rpi-bsp#3] opened 2021-12-20 16:41 UTC
E
RROR: wrlinux-image-std-1.0-r5 do_rootfs: Could not invoke dnf. Command '/home/madhanmohan/Desktop/build/tmp-glibc/work/rpi3_64-wrs-linux/wrlinux-image-std/1.0-r5/recipe-sysroot-native/usr/bin/dnf -v --rpmverbosity=info -y -c /home/madhanmohan/Desktop/build/tmp-glibc/work/rpi3_64-wrs-linux/wrlinux-image-std/1.0-r5/rootfs/etc/dnf/dnf.conf --setopt=reposdir=/home/madhanmohan/Desktop/build/tmp-glibc/work/rpi3_64-wrs-linux/wrlinux-image-std/1.0-r5/rootfs/etc/yum.repos.d --installroot=/home/madhanmohan/Desktop/build/tmp-glibc/work/rpi3_64-wrs-linux/wrlinux-image-std/1.0-r5/rootfs --setopt=logdir=/home/madhanmohan/Desktop/build/tmp-glibc/work/rpi3_64-wrs-linux/wrlinux-image-std/1.0-r5/temp --repofrompath=oe-repo,/home/madhanmohan/Desktop/build/tmp-glibc/work/rpi3_64-wrs-linux/wrlinux-image-std/1.0-r5/oe-rootfs-repo --nogpgcheck install dnf gdb gdbserver kernel-modules nfs-utils-client packagegroup-base-extended packagegroup-busybox-replacement packagegroup-wr-base packagegroup-wr-base-discrete-tools packagegroup-wr-base-net packagegroup-wr-boot packagegroup-wr-bsps packagegroup-wr-core-db packagegroup-wr-core-interactive packagegroup-wr-core-mail packagegroup-wr-core-net packagegroup-wr-core-perl packagegroup-wr-core-python packagegroup-wr-core-sys-util packagegroup-wr-core-util rpm run-postinsts' returned 1:
DNF version: 4.2.2
cachedir: /home/madhanmohan/Desktop/build/tmp-glibc/work/rpi3_64-wrs-linux/wrlinux-image-std/1.0-r5/rootfs/var/cache/dnf
Added oe-repo repo from /home/madhanmohan/Desktop/build/tmp-glibc/work/rpi3_64-wrs-linux/wrlinux-image-std/1.0-r5/oe-rootfs-repo
repo: using cache for: oe-repo
not found other for: 
not found modules for: 
not found deltainfo for: 
not found updateinfo for: 
oe-repo: using metadata from Mon 20 Dec 2021 04:32:30 PM UTC.
Last metadata expiration check: 0:00:01 ago on Mon 20 Dec 2021 04:32:32 PM UTC.
No module defaults found
No match for argument: gdbserver
Error: Unable to find a match

ERROR: Logfile of failure stored in: /home/madhanmohan/Desktop/build/tmp-glibc/work/rpi3_64-wrs-linux/wrlinux-image-std/1.0-r5/temp/log.do_rootfs.32618
ERROR: Task (/home/madhanmohan/Desktop/layers/wrlinux/wrlinux-distro/recipes-base/images/wrlinux-image-std.bb:do_rootfs) failed with exit code '1'

**Comment by rdanter** [comment] 2021-12-29 13:33
Can you tell me what steps you took to create the project and build, including any customisations you made?
Also, which version of WR Linux were you using (LTS/CI version and RCPL)?

**Comment by rdanter** [comment] 2023-08-18 08:58
Since there was no feedback on how to reproduce the issue, I am finally closing it.

**Closed as not planned by rdanter** 2023-08-18 08:58 UTC
